#!/bin/bash

source "$(dirname "$0")/lib/bash_common/init"

############################################################
# Import dependencies

deps=("bash_common" "mkheader")
import_dep "${deps[@]}"

export xdir=$(getxdir)
